config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users

  # root path 
  root 'home#index'

  # guest login 
  post '/users/guest_sign_in', to: 'home#guest_sign_in'

  # route for users
  resources :users do
    # route for movies
    resources :movies, only: %i(create edit update destroy)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user 
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
Top
<% end %>

<div class="bg-indigo-500 relative overflow-hidden h-screen">
    <%= image_tag "top-bg-image.jpg", class: 'absolute h-full w-full object-cover' %>
    <div class="inset-0 bg-black opacity-25 absolute">
    </div>
    <header class="absolute top-0 left-0 right-0 z-20">
        <nav class="container mx-auto px-6 md:px-12 py-4">
            <div class="md:flex justify-center items-center relative">
                <div class="flex justify-between items-center">
                    <div class="md:hidden">
                        <button class="text-white focus:outline-none" id="dropdown-trigger">
                            <svg class="h-12 w-12" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4 6H20M4 12H20M4 18H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                </path>
                            </svg>
                        </button>
                    </div>
                    <!-- dropdown menu -->
                    <ul class="hidden absolute left-0 top-20 w-62 rounded-md bg-gray-800 text-white px-3 py-3" id="dropdown-menu">
                      <li class="">
                        <%= link_to "ホーム", root_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                      </li>
                       <% if user_signed_in? %>
                       <li class="mt-3">
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                      </li>
                      <li class="mt-3">
                      <%= link_to user_path(current_user), class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' do %>
                      <i class="fas fa-user"></i> <%= current_user.email %>
                      </li>
                      <% end %>
                    <% else %>
                    <li class="mt-3">
                    <%= link_to "ログイン", new_user_session_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    </li>
                    <li class="mt-3">
                    <%= link_to "ユーザー登録", new_user_registration_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    <li>
                    <li class="mt-3">
                    <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    </li>
                    <% end %>
                    </ul>
                </div>
                <div class="hidden md:flex items-center">
                    <%= link_to "home", root_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    <% if user_signed_in? %>
                      <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                      <%= link_to user_path(current_user), class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' do %>
                      <i class="fas fa-user"></i> <%= current_user.email %>
                      <% end %>
                    <% else %>
                    <%= link_to "login", new_user_session_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    <%= link_to "register", new_user_registration_path, class: 'text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300' %>
                    <a class="text-lg uppercase mx-3 text-white cursor-pointer hover:text-gray-300">
                        Guest Login
                    </a>
                    <% end %>
                </div>
            </div>
        </nav>
    </header>
    <div class="container border-4 border-white rounded-lg mx-auto w-4/5 relative z-10 flex items-center py-16 my-24 md:my-32">
        <div class="w-full flex flex-col items-center justify-between relative z-10">
            <p class="flex flex-col items-center font-extrabold text-6xl text-center md:text-8xl text-white">
                動画の時間を愛そう。
            </p>
            <p class="flex flex-col max-w-lg text-center items-center font-extrabold text-lg mt-6 text-white">
            動画をみる時、人生は幸せ？それとも罪悪感？<br>
            PaiMovieLogは、学習と娯楽に費やした動画時間を入力し、<br>
            1日の、1ヶ月の、1年の動画時間を計測します。<br>
            PaiMovieLogは、動画の時間を貯金します。</p>
            <% if user_signed_in? %>
            <%= link_to "はじめる", user_path(current_user), class: 'block bg-gray-800 hover:bg-gray-900 py-3 px-4 text-lg text-white font-bold uppercase mt-10' %>
            <% else %>
            <%= link_to "login", new_user_session_path, class: 'block bg-gray-800 hover:bg-gray-900 py-3 px-4 text-lg text-white font-bold uppercase mt-5' %>
            <% end %>
        </div>
    </div>
</div>
<div class="md:flex justify-center mt-10 gap-4">
<div class="md:max-w-sm rounded overflow-hidden shadow-lg bg-gray-800 text-white py-4 mt-3">
      <i class="fas fa-video text-5xl text-red-400 ml-5"></i>
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">動画時間を入力</div>
        <p class="text-base">
         動画の視聴時間を入力することで動画に使った時間を可視化することが可能です。
        </p>
      </div>
    </div>
    <div class="md:max-w-sm rounded overflow-hidden shadow-lg bg-gray-800 text-white py-4 mt-3">
      <i class="fas fa-pencil-alt text-5xl text-yellow-400 ml-5"></i>
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">学習時間も娯楽時間も</div>
        <p class="text-base">
          動画は単に暇つぶしのためだけのものではありません。学習など有効的に活用し記録することで有意義と感じる心理的効果が期待できます。
        </p>
      </div>
    </div>
    <div class="md:max-w-sm rounded overflow-hidden shadow-lg bg-gray-800 text-white py-4 mt-3">
      <i class="fas fa-book text-5xl text-blue-400 ml-5"></i>
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">日記にも使える</div>
        <p class="text-base">
          ログ機能によりどんな動画を観たのかどんな感想を持ったのかを記録することも可能です。動画との人生を豊かにする日記となるでしょう。
        </p>
      </div>
    </div>
    </div>

    <script>
     'use strict';
     
     let trigger = document.getElementById('dropdown-trigger');

     trigger.addEventListener('click', function(){
       document.getElementById('dropdown-menu').classList.toggle('hidden');
     })
    </script>