config/routes.rb
Rails.application.routes.draw do
  # user management
  devise_for :users

  # root path 
  root 'home#index'

  # guest login 
  post '/users/guest_sign_in', to: 'home#guest_sign_in'

  # route for users
  resources :users do
    # route for movies
    resources :movies, only: %i(create edit update destroy)
  end


end

app/views/layouts/partial/_graph.html.erb
<div class="flex justify-center items-center h-screen w-full">
    <div class="w-full bg-white rounded shadow-2xl p-8 m-4 mb-48 text-black">
        <h1 class="block w-full text-center text-gray-800 text-2xl font-bold mb-6">グラフ</h1>
        <div class="graph-header flex justify-center">
          <div class="graph-time w-1/2">合計: <%= sum_times %>分
          <span class="block">(<%= to_hour %>時間)</span></div>
          <div class="graph-period w-1/2">
            <div class="relative">
    <!-- Dropdown toggle button -->
    <button class="flex items-center p-2 bg-white bg-gray-100 rounded-md">
        <span class="mr-4" id="dropdown-graph-trigger"><%= @user.movies_period(@period).keys.first %> - <%= @user.movies_period(@period).keys.last %><i class="fas fa-sort-down mb-1 ml-2"></i></span>
    </button>
    <!-- Dropdown list -->
    <div class="absolute z-10 left-0 top-10 py-2 mt-2 bg-white bg-gray-100 rounded-md shadow-xl w-44 hidden" id="dropdown-graph-menu">
    <%= link_to "週間", user_path(@user, period: 'week'), class: 'block px-4 py-2 text-sm text-gray-300 text-gray-700 hover:bg-gray-400 hover:text-white' %>
    <%= link_to "月間", user_path(@user, period: 'month'), class: 'block px-4 py-2 text-sm text-gray-300 text-gray-700 hover:bg-gray-400 hover:text-white' %>
    <%= link_to "年間", user_path(@user, period: 'year'), class: 'block px-4 py-2 text-sm text-gray-300 text-gray-700 hover:bg-gray-400 hover:text-white' %>
    </div>
</div> 
          </div>
        </div>
        <div class="graph-content">
            <%= line_chart @chart_movies %>
        </div>
    </div>
</div>

<script>
     'use strict';
     
     let graphTrigger = document.getElementById('dropdown-graph-trigger');

     graphTrigger.addEventListener('click', function(){
       document.getElementById('dropdown-graph-menu').classList.toggle('hidden');
     })
</script>

app/views/layouts/partial/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6 w-full z-10 pin-t">
		<div class="flex items-center flex-no-shrink text-white mx-auto lg:mr-6">
      <%= link_to root_path, class: 'text-white no-underline hover:text-white hover:no-underline' do %>
				<span class="text-2xl pl-2">PaiMovieLog</span>
			<% end %>
		</div>

		<div class="block lg:hidden">
			<button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-grey border-grey-dark text-white hover:text-white hover:border-white">
				<svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
			</button>
		</div>

		<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
			<ul class="list-reset lg:flex justify-end flex-1 items-center text-white">
				<li class="mr-3">
				<%= link_to "プロフィール", edit_user_registration_path, class: 'inline-block no-underline hover:text-underline py-2 px-4 lg:bg-gray-400 lg:rounded' %>
				</li>
				<li class="mr-3">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'inline-block no-underline hover:text-underline py-2 px-4 lg:bg-red-400 lg:rounded' %>
				</li>
			</ul>
		</div>
	</nav>

	<script>
		//Javascript to toggle the menu
		document.getElementById('nav-toggle').onclick = function(){
			document.getElementById("nav-content").classList.toggle("hidden");
		}
	</script>

app/views/layouts/partial/_log.html.erb
<!-- log content for sp -->
<div class="logs-wrapper-sp lg:hidden w-4/5 mx-auto mt-10">
<h2 class="text-3xl">Logs</h2>
<% @movies.each do |movie| %>
<div class="logs-content-sp border-l-2 border-gray-300 mt-10 px-4">
  <div class="logs-header-sp flex justify-center font-bold text-xl">
    <div class="logs-time-sp w-1/2 text-left">
    <% if movie.time.nil? %>
    0分
    <% else %>
    <%= movie.time %>分
    <% end %>
    </div>
    <div class="logs-date-sp w-1/2 text-right"><span class="mr-3"><%= time_ago_in_words(movie.created_at) %>前</span> 
    <%= link_to edit_user_movie_path(current_user.id, movie) do %>
    <i class="fas fa-pencil-alt text-blue-500"></i>
    <% end %>
    </div>
  </div>
  <div class="logs-memo-sp pt-5">
    <%= movie.memo %>
    <% if movie.image.attached? %>
      <div class="mt-3"><%= image_tag movie.resize_image %></div>
    <% end %>
  </div>
</div>
<% end %>
</div>
<!-- /log content for sp -->

<!-- log content fot pc -->
<div class="logs-wrapper-pc hidden w-4/5 mx-auto mt-10 lg:block">
<h2 class="text-3xl">Logs</h2>
<% @movies.each do |movie| %>
<div class="logs-content-pc mt-10 px-4 flex justify-center">
<div class="logs-date-pc w-1/3 font-bold text-lg text-gray-600 text-center">
 <%= time_ago_in_words(movie.created_at) %>前
</div>
<div class="w-2/3 border-l-2 border-gray-300 pl-2 text-lg">
 <div class="logs-time-pc">
     <% if movie.time.nil? %>
    <span>0分</span>
    <% else %>
    <span><%= movie.time %>分</span>
    <% end %>
    <%= link_to edit_user_movie_path(current_user.id, movie) do %>
  <i class="fas fa-pencil-alt text-blue-500 float-right"></i>
  <% end %>
</div>
  <div class="logs-memo-pc pt-3">
    <%= movie.memo %>
        <% if movie.image.attached? %>
      <div class="mt-3"><%= image_tag movie.resize_image %></div>
    <% end %>
  </div>
</div>
</div>
<% end %>
</div>
<!-- /log content for pc -->

app/views/layouts/partial/_movie_edit_form.html.erb
    <div class="w-full bg-white rounded p-8 m-4">
    <div class="text-center">
        <i class="fas fa-pencil-alt text-yellow-800 text-4xl"></i>
        </div>
        <h1 class="block w-full text-center text-gray-800 text-2xl font-bold mb-6 border-b-300 border-yellow-600 pb-3 mt-3">メモ編集</h1>
        <%= form_with model: @movie, url: user_movie_path(@user, @movie), class: 'text-black', local: true do |edit_movie| %>
        <%= render 'jas/shared/error_messages', object: @movie %>
            <div class="flex flex-col mb-4">
            <%= edit_movie.text_field :time, class: 'border py-2 px-3', placeholder: '時間（分）を入力してください' %>
            </div>
            <div class="flex flex-col mb-4">
            <%= edit_movie.text_area :memo, class: 'border py-2 px-3', placeholder: 'メモを加えてください', style: 'height: 150px; resize: none;' %>
            </div>
            <div class="flex flex-col mb-4">
            <%= edit_movie.file_field :image, class: 'border py-2 px-3' %>
            </div>
            <div class="flex justify-center gap-2">
            <div class="w-1/2">
              <%= link_to "削除", user_movie_path(@user, @movie), method: :delete, data: { confirm: 'Are you sure?' }, class: 'w-full block bg-red-500 hover:bg-red-700 text-white uppercase text-lg mx-auto p-3 rounded text-center' %>
            </div>
            <div class="w-1/2">
              <%= edit_movie.submit '更新', class: 'w-full block bg-blue-500 hover:bg-blue-700 text-white uppercase text-lg mx-auto p-3 rounded cursor-pointer' %>
            </div>
            </div>
            <%= link_to "戻る", user_path(@user), class: 'w-full block bg-gray-500 hover:bg-gray-700 text-white uppercase text-lg mx-auto p-3 rounded text-center mt-5' %>
        <% end %>
    </div>

app/views/layouts/partial/_movie_form.html.erb
<div class="flex justify-center items-center h-screen w-full">
    <div class="w-full bg-white rounded shadow-2xl p-8 m-4 mb-48">
        <h1 class="block w-full text-center text-gray-800 text-2xl font-bold mb-6">記録</h1>
        <%= form_with model: @user.movies.build, url: user_movies_path(@user), class: 'text-black', local: true do |new_movie| %>
        <%= render 'jas/shared/error_messages', object: new_movie.object %>
            <div class="flex flex-col mb-4">
            <%= new_movie.text_field :time, class: 'border py-2 px-3', placeholder: '時間（分）を入力してください' %>
            </div>
            <div class="flex flex-col mb-4">
            <%= new_movie.text_area :memo, class: 'border py-2 px-3', placeholder: 'メモを加えてください', style: 'height: 150px; resize: none;' %>
            </div>
            <div class="flex flex-col mb-4">
            <%= new_movie.file_field :image, class: 'border py-2 px-3' %>
            </div>
            <button class="w-full block bg-blue-400 hover:bg-teal-600 text-white uppercase text-lg mx-auto p-3 rounded" type="submit">記録する</button>
        <% end %>
    </div>
</div>